CREATE TABLE `check_in` (
                            `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
                            `elder_name` VARCHAR(50) NOT NULL COMMENT '老人姓名',
                            `elder_id` BIGINT NOT NULL COMMENT '老人ID',
                            `id_card_no` CHAR(18) NOT NULL COMMENT '身份证号',
                            `start_date` DATE NOT NULL COMMENT '入住开始时间',
                            `end_date` DATE COMMENT '入住结束时间',
                            `nursing_level_name` VARCHAR(50) NOT NULL COMMENT '护理等级名称',
                            `bed_number` VARCHAR(50) NOT NULL COMMENT '入住床位',
                            `status` TINYINT NOT NULL DEFAULT '0' COMMENT '状态 (0: 已入住, 1: 已退住)',
                            `sort_order` INT NOT NULL DEFAULT '0' COMMENT '排序编号',
                            `create_time` TIMESTAMP  DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                            `update_time` TIMESTAMP  DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
                            `create_by` VARCHAR(50)  COMMENT '创建人',
                            `update_by` VARCHAR(50)  COMMENT '修改人',
                            `remark` VARCHAR(255) COMMENT '备注',
                            PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `check_in_config` (
                                   `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
                                   `check_in_id` BIGINT NOT NULL COMMENT '入住表ID',
                                   `nursing_level_id` BIGINT NOT NULL COMMENT '护理等级ID',
                                   `nursing_level_name` VARCHAR(50) NOT NULL COMMENT '护理等级名称',
                                   `fee_start_date` DATE NOT NULL COMMENT '费用开始时间',
                                   `fee_end_date` DATE COMMENT '费用结束时间',
                                   `deposit` DECIMAL(10, 2) NOT NULL COMMENT '押金（元）',
                                   `nursing_fee` DECIMAL(10, 2) NOT NULL COMMENT '护理费用（元/月）',
                                   `bed_fee` DECIMAL(10, 2) NOT NULL COMMENT '床位费用（元/月）',
                                   `insurance_payment` DECIMAL(10, 2) NOT NULL COMMENT '医保支付（元/月）',
                                   `government_subsidy` DECIMAL(10, 2) NOT NULL COMMENT '政府补贴（元/月）',
                                   `other_fees` DECIMAL(10, 2) NOT NULL COMMENT '其他费用（元/月）',
                                   `sort_order` INT NOT NULL DEFAULT '0' COMMENT '排序编号',
                                   `create_time` TIMESTAMP  DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                   `update_time` TIMESTAMP  DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
                                   `create_by` VARCHAR(50)  COMMENT '创建人',
                                   `update_by` VARCHAR(50)  COMMENT '修改人',
                                   `remark` VARCHAR(255) COMMENT '备注',
                                   PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `contract` (
                            `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
                            `elder_id` INT NOT NULL COMMENT '老人ID',
                            `contract_name` VARCHAR(100) NOT NULL COMMENT '合同名称',
                            `contract_number` VARCHAR(50) NOT NULL COMMENT '合同编号',
                            `agreement_path` VARCHAR(255) NOT NULL COMMENT '协议地址（文件路径或URL）',
                            `third_party_phone` VARCHAR(20) NOT NULL COMMENT '丙方手机号',
                            `third_party_name` VARCHAR(50) NOT NULL COMMENT '丙方姓名',
                            `elder_name` VARCHAR(50) NOT NULL COMMENT '老人姓名',
                            `start_date` DATE NOT NULL COMMENT '开始时间',
                            `end_date` DATE NOT NULL COMMENT '结束时间',
                            `status` TINYINT NOT NULL DEFAULT '0' COMMENT '状态 (0: 未生效, 1: 已生效, 2: 已过期, 3: 已失效)',
                            `sign_date` DATE NOT NULL COMMENT '签约日期',
                            `termination_submitter` VARCHAR(50) COMMENT '解除提交人',
                            `termination_date` DATE COMMENT '解除日期',
                            `termination_agreement_path` VARCHAR(255) COMMENT '解除协议地址（文件路径或URL）',
                            `sort_order` INT NOT NULL DEFAULT '0' COMMENT '排序编号',
                            `create_time` TIMESTAMP  DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                            `update_time` TIMESTAMP  DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
                            `create_by` VARCHAR(50)  COMMENT '创建人',
                            `update_by` VARCHAR(50)  COMMENT '修改人',
                            `remark` VARCHAR(255) COMMENT '备注',
                            PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;